# -*- coding: utf-8 -*-
"""basit_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLupfs7Hjh__p0UoYGHZe4O9XLkWH9W-
"""

import requests
import json
import os
import time

knowledge_text = """
Space is a vast region beyond Earth’s atmosphere. It contains stars, planets, moons, asteroids, and galaxies.

Planets in our Solar System incluhde:
- Mercury: the smallest and closest to the Sun.
- Venus: very hot, covered in thick clouds.
- Earth: our home, the only known planet with life.
- Mars: called the Red Planet, possible future home for humans.
- Jupiter: the largest planet, famous for its Great Red Spot.
- Saturn: surrounded by beautiful rings.
- Uranus: spins on its side.
- Neptune: farthest planet, deep blue in color.

Other facts:
- The Moon is Earth’s natural satellite.
- The Sun is a star at the center of the Solar System.
- Astronauts travel to space using rockets.
- Black holes are regions where gravity is so strong that not even light can escape.
"""

def make_chunks(text, chunk_size=25):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size):
        chunks.append(" ".join(words[i:i + chunk_size]))
    return chunks


def find_relevant(query, knowledge_base):
    query_words = set(query.lower().split())
    matches = []
    for chunk in knowledge_base:
        chunk_words = set(chunk.lower().split())
        if not query_words.isdisjoint(chunk_words):
            matches.append(chunk)
    return matches


def rag_pipeline(question, knowledge_base):
    print("\n🔎 Searching the notes...")
    relevant = find_relevant(question, knowledge_base)

    if not relevant:
        return "⚠️ Sorry, I don’t know the answer from my notes."

    # Just return the most relevant parts
    answer = " ".join(relevant)
    return f"📘 From my notes: {answer}"


if __name__ == "__main__":
    knowledge_base = make_chunks(knowledge_text)
    print("🚀 Space Knowledge Chat (type 'exit' to quit)")
    while True:
        question = input("\nAsk me about space: ")
        if question.lower() == "exit":
            print("👋 Goodbye, Earthling!")
            break
        answer = rag_pipeline(question, knowledge_base)
        print("\n💡 Answer:", answer)